---
title: "eda-mahin"
output: html_document
---

PLOTS

1. Missingness Correlation
2. Review word cloud
3. Review pros and cons word count histogram


```{r}
pkg_needed <- c("tidyverse", 
                "lubridate", 
                "ggplot2",
                "ggcorrplot",
                "here",
                "corrplot",
                "vader",
                "tidytext",
                "stringr")
for (p in pkg_needed) {
  if (!requireNamespace(p, quietly = TRUE)) {
    install.packages(p)
  }
}
```

pros_words <- data %>%
  unnest_tokens(word, review_pros) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

ggplot(head(pros_words, 20), aes(x = reorder(word, n), y = n)) +
  geom_col() +
  coord_flip()

Reviews EDA

```{r}
library(here)
library(dplyr)
library(tidytext)
library(stringr)
data <- read.csv(
  here("data", "processed", "chatgpt_glassdoor_reviews_with_sector_revised.csv")
)

source("src/utils/data_helpers.R")
```


```{r}
## Review word count histogram
data <- Remove.Obvious.Columns(data)

data_wc <- data %>%
  mutate(
    pros_word_count = str_count(review_pros, "\\S+"),
    cons_word_count = str_count(review_cons, "\\S+")
  )




pros_words <- data %>%
  unnest_tokens(word, review_pros) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

pros_words
```



