---
title: "AMS597 Project Data Cleaning"
author: "Group 1"
date: "2026-03-12"
output: 
  pdf_document:
    number_sections: true
---

# Read Data
```{r}
setwd("~/glassdoor-company-reviews")
df <- read.csv("data/processed/chatgpt_glassdoor_reviews_with_sector_revised.csv")
head(df)
```


# Missing
```{r}
source("~/glassdoor-company-reviews/src/utils/data_helpers.R")

Missing.Check.By.Column(df)
```


# Process Employee Status

If ```employee_length``` is missing, then delete it. (4 rows)

If is current employee, then use rating_year instead of end_year to minus employee_length to calculate the start_year. After this step we make sure all missing of end_year are currently employees.

```{r}
library(tidyverse)
library(lubridate)

df <- df %>%
  # Remove rows where employee length is missing
  drop_na(employee_length) %>%
  
  # Create cleaned employment variables
  mutate(
    # Extract review year from rating_date
    rating_year = as.numeric(sub("[^0-9]*(\\d{4}).*", "\\1", rating_date)),
    
    # Fill missing employee type as Former
    employee_type = if_else(is.na(employee_type), "Former", employee_type),
    
    # TRUE if former employee, FALSE otherwise
    employee_job_quit = str_detect(
      employee_type,
      regex("^Former", ignore_case = TRUE)
    ),
    
    # Estimate start year
    employee_job_start_year = if_else(
      employee_job_quit,
      employee_job_end_year - employee_length,  # former employee
      rating_year - employee_length             # current employee
    )
  )

# Check remaining missing values by column
Missing.Check.By.Column(df)
```

```{r}
lengthvars <- c("employee_job_start_year", "employee_job_end_year", "employee_job_quit", "employee_length", "employee_type")
print(head(df[, lengthvars], 5))
```


